commerce_payment.commerce_payment_gateway.plugin.klarna_checkout:
  type: commerce_payment_gateway_configuration
  mapping:
    merchant_id:
      type: string
      label: 'Merchant ID'
    password:
      type: string
      label: 'Merchant Secret Key'
    live_mode:
      type: string
      label: 'Live mode'
    terms_path:
      type: path
      label: 'Terms path'
    language:
      type: sequence
      label: 'Language'
    update_billing_profile:
      type: sequence
      label: 'Update billing profile'
